spring:
  application:
    name: fmkj-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/hammerchain?characterEncoding=utf-8&useSSL=false
    # 配置初始化大小、最小、最大
    maxActive: 20
    initialSize: 1
    minIdle: 1
    # 配置监控统计拦截的filters
    filters: stat
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 校验语句
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    show-sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis-plus:
  mapper-locations: classpath*:/com/fmkj/user/dao/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.fmkj.user.dao.domain
  global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 2
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 0
      logic-not-delete-value: 1
      #自定义SQL注入器
      #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
logging:
  level:
     com.fmkj.user.dao: debug
server:
  port: 8078
feign:
  hystrix:
      enabled: true


#获取头像图片ip路径
userHeadImageIpPath: http://127.0.0.1:9898/userHead/

#存放头像图片物理路径
userHeadImagePath: E:\\apache-tomcat-8.5.32\\webapps\\userHead

#身份认证接口url
cardPath: https://way.jd.com/youhuoBeijing/test

#京东接口调用密匙
cardPwd: 8fda758a86044ca3a6b67f268c3964a6

#敏感词汇过滤接口url
wordPath: https://way.jd.com/tongchengyuan/minganci

#存放身份证照片物理路径
userCodeImagePath: E:\\huangs\\cardImages

#存放支付照片物理路径
userPayImagePath: E:\\huangs\\payImages

#公网ip:47.101.52.173
#测试ip:47.74.181.255
#获取身份证照片ip路径(实名认证后台活动图片ip地址)
userCodeImageIpPath: http://47.101.52.255:9898/image/

userPayImageIpPath: http://47.101.52.255:9898/payimage/